added HW for lesson3
AnnaNik553/geekshop pull request #3
Opened 2021-06-03 09:29 UTC by AnnaNik553

2021-06-03 14:53 UTC, Vokler requested changes

2021-06-03 14:53 UTC, Vokler commented on products/views.py
> +    context['products'] = Product.objects.all()
Лучше эти строчки занести сразу в context:
`context = {'title': 'GeekShop - Каталог', 'products': Product.objects.all(), 'categories': ProductCategory.objects.all()}`

2021-06-03 19:17 UTC, AnnaNik553 commented on products/views.py
> +    context['products'] = Product.objects.all()
Валерий, context исправила.

2021-06-04 07:55 UTC, Vokler approved these changes

2021-06-04 07:55 UTC, merged